workflows: fail if $pipestatus isn't 0 0
idk either!!

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -27,6 +27,9 @@ jobs:
             - name: Lint with black
               run: |
                   poetry run black --check . 2>&1 | awk "/^would reformat/ { print \"::error file=\" \$3 \"::doesn't have black's formatting\" }"
+                  # Github actions doesn't seem to respect $pipestatus, so forcefully fail
+                  # ¯\_(ツ)_/¯
+                  [[ $(echo $pipestatus) != "0 0" ]] && exit 1
 
             - name: Lint with isort
               run: |
